# workers: x + y + z + w
# demuxers: x

status: "status"
sink:
  coords: "coords"
  flights: "demux"

port: "6666"

server:
  url: "amqp://guest:guest@rabbitmq:5672/"

log:
  level: "error"

beater_port: 9000
