#Port to be used by the service
net_port: 10000

#Port used by the beater protocol
heartbeat_port: 9000

#All peers, including self
peers:
  prefix: peer
  # count: 3

#All containers to be monitored
containers:
  input:
    prefix: input
  output:
    prefix: output
  demux:
    prefix: demux_filter
    # count: x
  distance:
    prefix: distance_filter
    # count: y
  fastest:
    prefix: fastest_filter
    # count: z
  average:
    prefix: avg_filter
    # count: w
