#Port to be used by the service
net_port: 10000

#Port used by the beater protocol
heartbeat_port: 9000

#All peers, including self
peers:
  prefix: peer
  count: 3

#All containers to be monitored
containers:
  demux:
    prefix: demux_filter
    count: 1
  distance:
    prefix: distance_filter
    count: 1
  fastest:
    prefix: fastest_filter
    count: 1
  average:
    prefix: avg_filter
    count: 1
