
#Port to be used by the service
net_port: 10000

#Port used by the beater protocol
heartbeat_port: 9000

#All peers, including self
peers:
  - peer_name: 1
    net_name: peer1
  - peer_name: 2
    net_name: peer2
  - peer_name: 3
    net_name: peer3

#All containers to be monitored
containers:

- peer_name: demux_filter1
- peer_name: distance_filter1
- peer_name: fastest_filter1
- peer_name: avg_filter1
