
name: tp1
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
    networks:
      - testing_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  inputBoundary:
    container_name: input
    image: input_boundary:latest
    entrypoint: /inputBoundary
    networks:
      - testing_net
    environment:
      - IN_WORKERS=4
      - IN_DEMUXERS=1
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./cmd/inputBoundary/config.yaml:/config.yaml

  outputBoundary:
    container_name: output
    image: output_boundary:latest
    entrypoint: /outputBoundary
    networks:
      - testing_net
    environment:
      - OUT_WORKERS=4
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./cmd/outputBoundary/config.yaml:/config.yaml

  demuxFilter1:
    container_name: demux_filter1
    image: demux_filter:latest
    entrypoint: /demuxFilter
    networks:
      - testing_net
    environment:
      - DEMUX_ID=1
      - DEMUX_WORKERS_Q2=1
      - DEMUX_WORKERS_Q3=1
      - DEMUX_WORKERS_Q4=1
    volumes:
      - ./cmd/demuxFilter/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  distanceFilter1:
    container_name: distance_filter1
    image: distance_filter:latest
    entrypoint: /distanceFilter
    networks:
      - testing_net
    environment:
      - DISTANCE_ID=1
      - DISTANCE_DEMUXERS=1
    volumes:
      - ./cmd/distanceFilter/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  fastestFilter1:
    container_name: fastest_filter1
    image: fastest_filter:latest
    entrypoint: /fastestFilter
    networks:
      - testing_net
    environment:
      - FAST_ID=1
      - FAST_DEMUXERS=1
    volumes:
      - ./cmd/fastestFilter/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

  avgFilter1:
    container_name: avg_filter1
    image: avg_filter:latest
    entrypoint: /avgFilter
    networks:
      - testing_net
    environment:
      - AVG_ID=1
      - AVG_DEMUXERS=1
    volumes:
      - ./cmd/avgFilter/config.yaml:/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
