results:
  dir: "./client/results/"
  first: "first.csv"
  second: "second.csv"
  third: "thrid.csv"
  fourth: "fourth.csv"

datafile: "./client/data/test.csv"

coordsfile: "./client/data/airports-codepublic.csv"

server:
  addr: "server"
  data: "6666"
  results: "7777"