results:
  dir: "./results/"
  first: "first.csv"
  second: "second.csv"
  third: "thrid.csv"
  fourth: "fourth.csv"

datafile: "./data/test.csv"

coordsfile: "./data/airports-codepublic.csv"

server:
  addr: "127.0.0.1"
  data: "6666"
  results: "7777"