# id: i
# demuxers: x

status: "status"
source:
  eof: "demux.eof"
  average: "average"
  queue: "average"
sink:
  results: "results"

server:
  url: "amqp://guest:guest@rabbitmq:5672/"

log:
  level: "info"

beater_port: 9000
