# id: k
# demuxers: x

status: "status"
source:
  eof: "demux.eof"
  queue: "fastest"
sink:
  results: "results"

server:
  url: "amqp://guest:guest@rabbitmq:5672/"

log:
  level: "info"

beater_port: 9000
