exchange:
  first: "stops"
  second: "distance"
  third: "duration"
  fourth: "avg"
  agregator: "results"

workers:
  first: 1
  second: 2
  third: 1
  fourth: 1
  
source: "amqp://guest:guest@localhost:5672/"

server:
  dataport: "6666"
  resultsport: "7777"