exchange:
  first: "stops"
  second: "distance"
  third: "fastest"
  fourth: "avg"
  agregator: "results"
  status: "status"


  
source: "amqp://guest:guest@rabbitmq:5672/"

server:
  dataport: "6666"
  resultsport: "7777"