exchange:
  first: "stops"
  second: "distance"
  third: "duration"
  fourth: "avg"
  agregator: "results"
  status: "status"

workers:
  first: 0
  second: 2
  third: 0
  fourth: 0
  
source: "amqp://guest:guest@localhost:5672/"

server:
  dataport: "6666"
  resultsport: "7777"