# demuxers: x

status: "status"
source:
  coords:
    exchange: "coords"
    queue: "coords"
  flights:
    eof: "demux.eof"
    queue: "distance"
sink:
  results: "results"

server:
  url: "amqp://guest:guest@rabbitmq:5672/"

log:
  level: "info"

beater_port: 9000
