data:
  coords: "client/data/airports-codepublic.csv"
  flights: "client/data/test.csv"

results:
  dir: "client/results/"
  files:
    - "first.csv"
    - "second.csv"
    - "third.csv"
    - "fourth.csv"

server:
  input: "input:6666"
  output: "output:7777"

log:
  level: "info"
