# workers:
#   q2: y
#   q3: z
#   q4: w

status: "status"
source:
  queue: "demux"
sink:
  distance: "distance"
  fastest: "fastest"
  average: "average"
  results: "results"
  eof: "demux.eof"

server:
  url: "amqp://guest:guest@rabbitmq:5672/"

log:
  level: "info"

beater_port: 9000
